// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfbdWserGHyWdR4RucYx9lC_k1-GibS8w',
    appId: '1:567458908653:web:cc7ecc9afe205249933fe4',
    messagingSenderId: '567458908653',
    projectId: 'kamalaupdate-de690',
    authDomain: 'kamalaupdate-de690.firebaseapp.com',
    storageBucket: 'kamalaupdate-de690.firebasestorage.app',
    measurementId: 'G-3LLQR6T2G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvENhrTUyj_e5F7AdjTCujMd0QmiLusO4',
    appId: '1:567458908653:android:90e218ba4dbe3551933fe4',
    messagingSenderId: '567458908653',
    projectId: 'kamalaupdate-de690',
    storageBucket: 'kamalaupdate-de690.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW2yZ9xOxbdwYpRVPEw26a2s1Bly9M09A',
    appId: '1:567458908653:ios:85257e2708030f41933fe4',
    messagingSenderId: '567458908653',
    projectId: 'kamalaupdate-de690',
    storageBucket: 'kamalaupdate-de690.firebasestorage.app',
    iosBundleId: 'com.example.kamalaUpdate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW2yZ9xOxbdwYpRVPEw26a2s1Bly9M09A',
    appId: '1:567458908653:ios:85257e2708030f41933fe4',
    messagingSenderId: '567458908653',
    projectId: 'kamalaupdate-de690',
    storageBucket: 'kamalaupdate-de690.firebasestorage.app',
    iosBundleId: 'com.example.kamalaUpdate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfbdWserGHyWdR4RucYx9lC_k1-GibS8w',
    appId: '1:567458908653:web:b7771e174088ae0a933fe4',
    messagingSenderId: '567458908653',
    projectId: 'kamalaupdate-de690',
    authDomain: 'kamalaupdate-de690.firebaseapp.com',
    storageBucket: 'kamalaupdate-de690.firebasestorage.app',
    measurementId: 'G-P7KMQPRG6B',
  );
}
